// Code generated by capnpc-go. DO NOT EDIT.

package ww

import (
	schemas "capnproto.org/go/capnp/v3/schemas"
)

const schema_e82706a772b0927b = "x\xda\x120r`1\xe4Mgd`\x0a\x14`e" +
	"c\xd0\x06\x04\x00\x00\xff\xff\x111\x01\xc6"

func RegisterSchema(reg *schemas.Registry) {
	reg.Register(&schemas.Schema{
		String:     schema_e82706a772b0927b,
		Nodes:      []uint64{},
		Compressed: true,
	})
}
